### ISSUE TITLE
Can we support the opposite conversion?

### ISSUE THREAD

**Issue by remorses** [TLevesque/import-2-require#4]
convert from `require` to `import`

i think a lot of code could be reused to do the same thing inversed

**Comment by TLevesque** [comment]
Hi, there is already some vscode extension doing "require" to "import syntax, like "Require To Import Syntax". 
I've done quickly this extension because none was doing the conversion the other way, and it made my work easier for a server downgrade, but normally people will upgrade their syntax instead more than downgrading it ;)
